# file: .github/workflows/show-directory.yml
name: triplework.yml
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозитори
      - uses: actions/checkout@v4
      # run – произвольная bash-команда
      # сетап проекта
      - run: make install
      # Запуск тестов 
      - run: make test
      # Запуск линтера 
      - run: make lint  

